### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by siordache** [PaulWinstone/demoModule#1]
1. There is no module-info.java in your demo project. Does your application use the Java Module System? (You don't have to use it if you don't need it.)
2. Do you use Eclipse only as your IDE? Or are you developing an [Eclipse RCP](https://wiki.eclipse.org/Rich_Client_Platform) application?
3. Do you have different DLLs for different customers? Or the same set of DLLs for all of them?
4. What is your final goal? To produce a zip of the fat jar? Or an installer created by the [jpackage tool](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A)?

**Comment by PaulWinstone** [comment]
1. This is the biggest question, I missed the module-info.java by accident from the demo - but its a good question. Is it best to use the Java Module System for long term support with the beryx.jlnk plugin to wrap up the legacy jars. JavaFX works well with the Java Module System and jlink will minimise total size. I have a full module-info.java for the application but it took work as the legacy jars are not modularised and some packages clash.
2. I use Eclipse only as my IDE.
3. Same DLLs for all customers
4. Final goal is a jpackageImage ie native windows exe but no installer. Extract and run.

**Comment by siordache** [comment]
It seems that your application doesn't really need the Java Module System, so I suggest to leave it non-modularized (that is, without a module-info.java). This way, you will no longer have issues with legacy jars and split packages. You can still use jlink and jpackage, so there are no downsides.

I will adjust this project accordingly and I will send a pull request in the next few days.

**Comment by PaulWinstone** [comment]
Thank you - staying non-modularized keeps it simple

Eclipse / Buildship are not robust with Modules - flaky with modules not updating in eclipse UI based on gradle dependencies and automatic modules from legacy jars - of which I have about 20


I have put off moving from Java ~8u172 for a long time

Successfully pulling in JavaFX and OpenJDK have caused me the main problem which is why I tried using the Java Module System


I judged that OpenJDK 14 was a good time to jump forward

I am using bellsoft OpenJDK at present as that had JavaFX packaged but I would prefer to let gradle pull in JavaFX thru the plugin. Your help with JavaFX makes it all work.


Hopefully it's a useful general example for others.



Best Regards



Paul Winstone

Solutions Consultant



Mobile     +44 77 99 647 603

Skype        paul.winstone.intertek

www.intertek.com<http://www.intertek.com/>



[cid:image003.png@01D2AFAA.CA3D93E0]



Intertek

N123

Wilton Centre

Redcar

Cleveland

TS10 4RF

United Kingdom





________________________________

**Comment by siordache** [comment]
How do you use the DLLs? With JNI or with JNA?

**Comment by PaulWinstone** [comment]
*   run java with argument -Djava.library.path=resources\dllDirectory
  *   load the dll by name System.loadLibrary("DLLName")
  *   access dll method by java declaration public static native short method();


Best Regards

Paul Winstone
Solutions Consultant

Mobile     +44 77 99 647 603
Skype        paul.winstone@intertek.com<mailto:paul.winstone@intertek.com>
www.intertek.com<http://www.intertek.com/>

**Comment by PaulWinstone** [comment]
The basic structure is in place and works well.

**Comment by PaulWinstone** [comment]
Hi Serban

Thanks for the help, I have added some more customisation for customer name and version on build, package and installer. Very neat solution.

What is the best way to fins out if this build.gradle is the best for eclipse buildship.

**Comment by siordache** [comment]
I don't know how to find out if this is the best build.gradle, I have only limited experience whith eclipse buildship.
